version: '1.0'

services:
  client:
    container_name: react-client
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
    networks:
      - appnetwork
    volumes:
      - ./client:/app
    depends_on:
      - server-nestjs

  server-nestjs:
    container_name: nestjs
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
      - "9229:9229"
    networks:
      - appnetwork
    volumes:
      - ./server:/app
    depends_on:
      - mariadb
      - redis
    environment:
      - CHOKIDAR_USEPOLLING=true

  redis:
    container_name: redis
    image: redis
    ports:
      - "6379:6379"
    networks:
      - appnetwork

  mariadb:
    container_name: mariadb
    image: mariadb:11.2
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: excel_upload_tasks
      MYSQL_USER: ezuser
      MYSQL_PASSWORD: ezpass
    networks:
      - appnetwork
    volumes:
      - ez-mariadb-data:/var/lib/mysql
      - ./sql:/docker-entrypoint-initdb.d

networks:
  appnetwork:
    driver: bridge

volumes:
  ez-mariadb-data:
